### ISSUE TITLE
why filtering?

### ISSUE THREAD

**Issue by sassbalint** [spyysalo/wiki-bert-pipeline#2]
Quite a quality piece of code. :+1: 

__Please help me to see the purpose and details of [__filtering__](https://github.com/spyysalo/wiki-bert-pipeline/blob/master/scripts/filterdocs.py) clearly.__

1. Why do you use filtering at all?
2. Do you risk good quality of the pretrained model by disabling it? _Do you have some numbers how much?_
3. Does filtering work _per document_? I.e. if some measure is not OK, then the whole document is thrown out? 
3. How did you come to the specific numbers you use in the [__config__](https://github.com/spyysalo/wiki-bert-pipeline/blob/master/config/filter.sh)?
4. What is `--avg-len`? [I do not quite get the idea.](https://github.com/spyysalo/wiki-bert-pipeline/blob/d41970c9e1b71f4f566529cb1221034e42d3c432/scripts/filterdocs.py#L52-L53)
5. In our case, using your filtering script with your config __we lose quite a large part of our corpus.__ So we plan to _adjust_ some config settings. According to your experience, what do you think which config values should remain unchanged for some theoretical reason and which can be freely adjusted?
6. Is this whole filtering idea yours or taken from a publication of someone else? In both cases, point me please to the relevant literature. 

Thanks.
A participant of FinTAL2006. :)

**Comment by sassbalint** [comment]
Provide some info on the above, if possible, please.

**Comment by spyysalo** [comment]
Thanks, and apologies for the late response! ([Paper](https://ep.liu.se/ecp/178/001/ecp2021178001.pdf) was just presented now.) Filtering is probably not really required for clean data (such as most Wikipedias), but allows the pipeline to be adapted for noisier input (such as web data). We only trained one model for each language, so we unfortunately don't have experimental support for including it. Most works pretraining on noisy data include some form of filtering. These specific filters are ours, based on common ideas in previous work. Please do adjust the filters according to what works for you, or disable them entirely -- these settings are just what worked for our data. Finally, `--avg-len` takes out  documents that have a low average "sentence" length, which in Wikipedia should mostly filter list pages and similar.
